### ISSUE TITLE
Version 1.6.2.1 typo (syntax error)

### ISSUE THREAD

**Issue by ddrury** [JustCarmen/justlight#10]
Navmenu.php line 437 should read

    $onclick = $submenu->getOnclick() ? 'onclick="' . $submenu->getOnclick() . '"' : "";

(braces after first getOnclick)

**Comment by JustCarmen** [comment]
I have fixed with this commit: https://github.com/JustCarmen/justlight/commit/af855dee535f72a16121ada9ff308bf7a2972a2f

Since the onclick call is not really necessary there I have removed it.
