### ISSUE TITLE
ERROR 8: Undefined property: WT_Menu::$getOnclick

### ISSUE THREAD

**Issue by jpoole317** [JustCarmen/justlight#12]
This error occurs when I click "Default Individual" on Homepage.
ERROR 8: Undefined property: WT_Menu::$getOnclick
0 Error occurred on line 437 of file navmenu.php in function getModuleMenus
1 called from line 91 of file functions.php in function getJLNavMenu
2 called from line 116 of file header.php in function require
3 called from line 163 of file Page.php in function pageHeader
4 called from line 43 of file individual.php

Notice: Undefined property: WT_Menu::$getOnclick in /home/pettyp7/public_html/PettypoolTree/themes/justlight/theme-1.6.2/navmenu.php on line 437

**Comment by JustCarmen** [comment]
This error is fixed in the latest release.

https://github.com/JustCarmen/justlight/releases/tag/1.6.2.2
