### ISSUE TITLE
Fixes for mobile

### ISSUE THREAD

**Issue by oddityoverseer13** [JustCarmen/justlight#14]
First, I want to say this theme is very nice. Specifically, I like that you used bootstrap, and I really like that you designed for the mobile experience. That said, I found a couple visual bugs on my phone.

(FYI: I'm using a Samsung Galaxy Note 3. Also, I'm viewing [this page on my Webtrees install](http://www.kniffin.us/webtrees/individual.php?pid=P314&ged=Kniffin).)

- The button for the right sidebar is mostly cut off. I have to zoom out to press it.
- The nav bar is too tall. I'd say you can remove margin-top from ".navbar-header", and decrease main div's top padding to 50px.
- The lines in the Facts and events tab are not wrapping at the width of the screen.
- Not sure if you can control it, but the params for the tab control seems a little off. Eg: The third tab (the first hidden one) is Sources. It can definitely fit in the space between Families and the arrow. I hope that makes sense.

That's all I noticed right now. If I see anything else, I'll let you know. Also, let me know if screenshots would help.

**Comment by JustCarmen** [comment]
Thanks for your feedback. Although the theme is fully functional, the development of this theme is still work in progress. Especially regarding mobile experience there are certainly several improvements to make. Your list will help me with that. I will look into the issues.

**Comment by JustCarmen** [comment]
These issues has been fixed during development for the next version.
