### ISSUE TITLE
Tabbladen niet aanklikbaar

### ISSUE THREAD

**Issue by MichielB79** [JustCarmen/justlight#15]
Beste Carmen,

Ik maak, met veel plezier, gebruik van  het JustLight thema. Na het upgraden naar de nieuwste webtrees versie en het upgraden van het thema lijken de linkjes van de tabbladen niet meer aanklikbaar. Bijvoorbeeld:
http://www.beckschebe.nl/webtrees/individual.php?pid=I0024&ged=beckschebe

Als je van 'Feiten en gebeurtenissen' naar 'Gezinnen' wilt dan gebeurt er niets. Met andere thema's werkt het wel (maar die wil ik natuurlijk niet gebruiken :) ). Ik ervaar dit probleem zowel in Microsoft Edge als in Google Chrome.

Is hier wellicht een oplossing voor?

Alvast bedankt voor je reactie!

Groet, Michiel Beckschebe

**Comment by JustCarmen** [comment]
Hallo Michiel,

Ik heb je link getest in zowel Chrome als Microsoft Edge en bij mij werken de tabbladen gewoon. Ik moet de fout kunnen reproduceren om een oplossing te vinden.

Ik heb daarom meer informatie nodig. Wat voor console gebruik je (pc, tablet, telefoon). Welke operating system (windows 10 neem ik aan, maar als het anders is hoor ik het graag). Welke browser versie?

**Comment by MichielB79** [comment]
Ik gebruik een laptop met windows 10 home, 64 bits.
Google Chrome: Versie 48.0.2564.97 m
Microsoft Edge: Versie 20.10240.16384.0

De knoppen zien er ook wat anders uit dan vroeger volgens mij. Minder hoog dan voorheen.

In ieder geval bedankt voor je snelle reactie. 
Als je het niet kunt reproduceren is het jammer, schijnbaar ligt het aan mijn eigen computer gezien het feit dat het bij jou zelf wel werkt.

**Comment by MichielB79** [comment]
Begrijpen doe ik het niet, maar het lijkt weer te werken, de tabbladen komen weer onder elkaar te staan ipv naast elkaar (zie afbeelding):

![knipsel](https://cloud.githubusercontent.com/assets/9165344/12698616/cce9526a-c7a1-11e5-977a-dcfa60893c26.jpg)

Dus voor mij heeft het zichzelf opgelost...

**Comment by JustCarmen** [comment]
Nee, het klopt niet. In het JustLight thema zijn de tabbladen omgebouwd naar panels, zodat ze ook op smallere devices goed werken. Als ìk op jouw site kijk, zie ik dit:

![fireshot screen capture 098](https://cloud.githubusercontent.com/assets/5641963/12699291/83f70812-c7b6-11e5-9cc4-5059781e7bf6.png)

De panels bestaan sinds versie 1.7.0, dus het is ook niet iets nieuws in de laatste versie.

Dus wat mij betreft nog niet opgelost ;). Ik laat dit issue openstaan en zal bij tijd en gelegenheid is gaan uitzoeken of ik erachter kan komen waar dit probleem door veroorzaakt wordt.
