### ISSUE TITLE
Links are exposed during webpage printing

### ISSUE THREAD

**Issue by imskriaz** [JustCarmen/justlight#18]
Since webtrees supports printing directly any page from tree website. I have tried the same in my website but all links are getting exposed. Attached
[Print.pdf](https://github.com/JustCarmen/justlight/files/215009/Print.pdf)

Is it any bug....

**Comment by JustCarmen** [comment]
Forgot to close this issue. It is fixed with commit https://github.com/JustCarmen/justlight/commit/254abd6c0c3120feda3e1ddc6cc4e14f0841a388
