### ISSUE TITLE
Suggestion to hide the media menu when media objects are protected by settings

### ISSUE THREAD

**Issue by mpwt** [JustCarmen/justlight#20]
If I restrict the access to f.i. media object by privacy restrictions it would by useful to hide the complete media menu if the user is not authorized to see it. I use the following code additions to do this:
![media1](https://cloud.githubusercontent.com/assets/16311627/15992567/83b66550-30cf-11e6-8ff3-10eb3d3cb9eb.png)

```
	if (Auth::check()) {
		if (count($folders) > 1) {
			$menu = new Menu(/* I18N: Main media menu */ I18N::translate('Media'), '', 'menu-media');

			foreach ($folders as $key => $folder) {
				if ($key !== $MEDIA_DIRECTORY) {
					$submenu = new Menu(ucfirst($folder), 'medialist.php?' . $this->tree_url . '&amp;action=filter&amp;search=no&amp;folder=' . Filter::escapeUrl($key) . '&amp;sortby=title' . $show_subfolders . '&amp;max=20&amp;columns=2&amp;action=submit', 'menu-mediafolder');
					$menu->addSubmenu($submenu);
				}
			}
		} else { // fallback if we don't have any subfolders added to the list
			$menu = new Menu(/* I18N: Main media menu */ I18N::translate('Media'), 'medialist.php?' . $this->tree_url, 'menu-media');
		}
		return $menu;

	} else {
		return null;
	}
	}
```
![media2](https://cloud.githubusercontent.com/assets/16311627/15992569/8a7cc94c-30cf-11e6-81ff-42132e932023.png)

**Comment by JustCarmen** [comment]
This doesn't work since it will always hide the media menu from non-logged in visitors even without using any privacy restrictions.

In the default webtrees theme the media-menu isn't hidden either in this case.

So I have used a different approach.
