### ISSUE TITLE
Default images

### ISSUE THREAD

**Issue by carlluiz** [JustCarmen/justlight#21]
Hi,
How do I modify the default images: "silhouette ..... png", and favicon, of the JustLight theme?
I'm not finding all the default images.
Thanks.

**Comment by JustCarmen** [comment]
The silhouette icons, like most icons in the JustLight theme are font icons. So these are not real images but fonts.

But you can replace these font icons with real images. Say you want to change the male silhouette font icon with one of your own images:

Look for the current style of the icon:

```
.icon-silhouette-M:before {
	content: "\e602";
	font-family: "icomoon";
	font-size: 48px;
}
```
Replace it with:
```
.icon-silhouette-M {
    background-image: url(images/icon-silhouette-m.png); /* or whatever the name of your image is */
	height: /* the height of your image */
	width: /* the width of your image */
}
```
Place the image in the folder images in the css folder.

The favicons can be found in the root of the css folder. Just replace these with your own and it should work.

**Comment by carlluiz** [comment]
Thank you very much
