### ISSUE TITLE
Hide, remove some features

### ISSUE THREAD

**Issue by carlluiz** [JustCarmen/justlight#22]
Hi JustCarmen, sorry to bother again,
My doubt is: On the top-menu -> REPORTS... How could I remove from the list, feature like CEMETERY for example?

I would like to remove this option from the MENU>REPORTS, but I don't know how to do it. I'm building the family tree just for fun among relatives of my family, but certain options are a bit sad to see, such as "cemetery, "death" ... I will not set search engines for our family tree. It will be only for some relatives to have access, to review pictures and some interesting things.

The webtrees is very professional, very cool, very fun to build, but it's a pity not to have a more simplified version or a theme with the option to hide these kind of items ("cemetery, "death", etc.) to avoid be seen.

Thanks a lot.

**Comment by JustCarmen** [comment]
Hi this is not a theme specific option. You can hide one or more reports from the menu by going into the Control Panel - menu Modules - Reports. For every single report you can set who can view the report (visitor, members, managers or hide from everyone)

**Comment by carlluiz** [comment]
I need to learn more... it's more easy than I expect.
Thank you very much.
