### ISSUE TITLE
New module?

### ISSUE THREAD

**Issue by carlluiz** [JustCarmen/justlight#23]
Hi,
Is there already a module that instead of only the "Save Clippings" of Webtrees (save to the hard drive), this module give to us the possibility to also send the link, or file/attachment, to an Email Client software (like Office Outlook)?

**Comment by JustCarmen** [comment]
No, as far as I know a module like this doesn't exist. But you can do do a feature request at the webtrees forum.

However I see you have already asked this question twice at the webtrees issue tracker: https://github.com/fisharebest/webtrees/issues/1060 and https://github.com/fisharebest/webtrees/issues/1065. But I don't give you much change. I personally don't see the benefit of such a module and I think the webtrees developers don't see it either.
