### ISSUE TITLE
error on calculated dates

### ISSUE THREAD

**Issue by Summibuxtehude** [JustCarmen/justlight#26]
Hello,

I use justlight (1.7.8) on webtrees 1.7.8 (PHP 7).
While editing date of birth (e.g. CAL 1710) justlight changes it to 17 OCT 2016.
The same effect while using the other terms of calculated dates (only complete dates works correctly).
Before I changed to PHP 7 (PHP 5.6) the input (e.g. CAL 1710) was deleted, so I can save nothing.

Best regards
Hauke Sumfleth

**Comment by JustCarmen** [comment]
Hi this was caused by the datetimepicker I recently implemented. It turned out it cannot work with the date qualifiers we often use. I couldn't find a solution, so I have removed it https://github.com/JustCarmen/justlight/commit/35b5525ffa9eef09d1d4f13849ef0dcfc5e7b752

**Comment by JustCarmen** [comment]
I have made a new release because of this bug

https://github.com/JustCarmen/justlight/releases/tag/1.7.8.1
