### ISSUE TITLE
Can't create Reports 

### ISSUE THREAD

**Issue by gnilebein** [JustCarmen/justlight#29]
I can't create any type of report when justlight theme is active. I can not select a person and webtrees show me only the string "undefined" (Screenshot: http://imgur.com/a/w3mKD:)

My Setup:
Webserver: Nginx
PHP: 7.0 via Fastcgi

No errors in PHP or Webserver Error log.

**Comment by JustCarmen** [comment]
What version of the theme do you use?

This was a bug I've fixed more then 6 months ago...

**Comment by gnilebein** [comment]
Ok, it seems that my theme version was to old. But where can i see the version number? 

Is there any posibility to check if there is an theme update?

**Comment by JustCarmen** [comment]
> But where can i see the version number?

Control panel - module administration.  You can find the version number in the module description.

> Is there any posibility to check if there is an theme update?

Unfortunately webtrees doesn't offer a possibility to auto upgrade custom modules, but it is good practice to check if an update of a custom module is available after an update of webtrees. The link in the module description leads to the module page on my website where you can find the version number of the latest release at the top of the page (below the title). You can also take a look in the release section here on Github.
